### ISSUE TITLE
OSX RPATH not being set correctly for CMake external project shared libraries

### ISSUE THREAD

**Issue by jakebolewski** [elemental/Elemental#61] opened 2015-04-22 18:35 UTC

**Comment by poulson** [comment] 2015-04-23 17:25
Ugh. I think I'm going to have to buy a Mac to reliably handle this.

**Comment by justusc** [comment] 2015-04-23 17:37
Join the dark side of the force!

**Comment by poulson** [comment] 2015-04-23 23:18
I'm flying dark on this one, but hopefully this changeset fixes the issue for metis and parmetis: https://github.com/elemental/Elemental/commit/8a75f38c2b45e4037e2c4843b5f6ad73c1d0a917

**Comment by poulson** [comment] 2015-04-25 01:37
I closed since @jakebolewski claims that the issue is now fixed for him.

**Closed** 2015-04-25 01:37 UTC
