### ISSUE TITLE
Building on Mira fails

### ISSUE THREAD

**Issue by justusc** [elemental/Elemental#75] opened 2015-06-22 18:30 UTC
When building on BG/Q (Mira), I see the following configure warnings:

```
CMake Warning (dev) at cmake/external_projects/ElMath/ParMETIS.cmake:81 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  cmake/external_projects/ElMath.cmake:291 (include)
  CMakeLists.txt:332 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/external_projects/ElMath/ParMETIS.cmake:82 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  cmake/external_projects/ElMath.cmake:291 (include)
  CMakeLists.txt:332 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Including /gpfs/mira-fs0/projects/DynamicPro/justusc/install/elemental/include for external ParMETIS
-- Appending /home/justusc/src/elemental/external/pmrrr/include for PMRRR's headers
CMake Warning (dev) at external/pmrrr/CMakeLists.txt:77 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:404 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/justusc/build/elemental
```

and build errors:

```
Scanning dependencies of target sandbox-test
[100%] Building CXX object CMakeFiles/sandbox-test.dir/sandbox/test.cpp.o
Linking CXX executable bin/sandbox-test
/soft/compilers/bgclang/r238097-20150523/binutils/bin/ld: attempted static link of dynamic object `/gpfs/mira-fs0/projects/DynamicPro/justusc/install/elemental/lib/libparmetis.so'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/sandbox-test] Error 1
make[1]: *** [CMakeFiles/sandbox-test.dir/all] Error 2
make: *** [all] Error 2
```

It appears that ParMETIS is being built as a static library, despite the fact that configure warnings says otherwise. The pmrrr library does appear to be a static library, though the warning is a little annoying.

**Comment by poulson** [comment] 2015-06-22 20:28
These errors were caused by Elemental assuming that ``BUILD_SHARED_LIBS`` determined whether or not shared or static libraries were built. I have committed a simple changeset which checks the global property ``TARGET_SUPPORTS_SHARED_LIBS`` and forces ``BUILD_SHARED_LIBS`` to ``OFF`` if the property is not set to true.

**Closed by poulson** 2015-06-22 20:28 UTC
